name = "crux-api"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "crux-db"
database_id = "7dd10925-be2f-4e64-bc4d-ba30a7af09f3"
